spring:
  application:
    name: api-gateway
  #cloud注册中心
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#  session:
#    store-type: redis
#  redis:
#    host: 127.0.0.1
#    database: 0
#    port: 6379

server:
  port: 8082
  session:
    timeout: 300
#eureka:
#  instance:
#    hostname: gateway
#  client:
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
zuul:
  ignored-services: microservice-provider-user                        # 需要忽视的服务(配置后将不会被路由)
  sensitiveHeaders:                                                   # 使用空来覆盖默认值
  routes:
#    institution:                                                      # 可以随便写，在zuul上面唯一即可；当这里的值 = service-id时，service-id可以不写。
#      path: /api/institution/**                                       # 想要映射到的路径
#      service-id: institution-service                                 # Eureka中的serviceId
#      strip-prefix: false
#    usemanage:
#      path: /api/system/**
#      service-id: usermanage-service
#      strip-prefix: false
    admin:
      path: /op/**
      url: http://127.0.0.1:8081

